In [1]:
import pandas as pd
import numpy as np
from scipy.stats import norm, t
import riskmgmlib as rml

In [2]:
cov_matrix = pd.read_csv('problem3_cov.csv')
cov_matrix = list(cov_matrix.values)
er = pd.read_csv('problem3_ER.csv')
rf = er.RF.values[0]

In [4]:
print(cov_matrix)

[array([0.0319209 , 0.02913003, 0.03203832]), array([0.02913003, 0.03432744, 0.03322408]), array([0.03203832, 0.03322408, 0.04152399])]


In [5]:
print(er)

      RF  Expected_Value_1  Expected_Value_2  Expected_Value_3
0  0.045          0.136372          0.139753          0.149213


In [6]:
data4_returns = pd.read_csv('problem4_returns.csv', index_col=3)
data4_weights = pd.read_csv('problem4_startWeight.csv')

In [7]:
data4_returns.head()

Asset1    Asset2    Asset3
Date                                    
2023-04-12  0.008024 -0.044177 -0.041222
2023-04-13 -0.017037  0.043223 -0.105578
2023-04-14  0.037744  0.017898 -0.007105
2023-04-15  0.044493 -0.033881  0.002944
2023-04-16 -0.052557  0.027637 -0.032206

In [8]:
data4_weights.head()

weight1   weight2   weight3
0  0.432265  0.155492  0.412242

In [9]:
data4_weights = list(data4_weights.values[0])
stocks = ['Asset1', 'Asset2', 'Asset3']
attribution, weight = rml.ex_post_contribution(data4_weights, stocks, data4_returns)

/Users/yanghaochen/Desktop/fintech545/Final_pre/riskmgmlib.py:413: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Attribution = Attribution.append(pd.DataFrame({


In [10]:
print(weight)
print("")
#b,c
print(attribution)

[[0.43226518 0.15549249 0.41224233]
 [0.44480495 0.15171745 0.4034776 ]
 [0.45716808 0.16549373 0.37733819]
 [0.46624717 0.16555259 0.36820024]
 [0.47921907 0.15739076 0.36339018]
 [0.46930371 0.16718065 0.36351564]
 [0.46969817 0.16270907 0.36759276]
 [0.42953883 0.17382824 0.39663293]
 [0.4201786  0.16851823 0.41130318]
 [0.40786885 0.16518321 0.42694794]
 [0.43319934 0.16759738 0.39920328]
 [0.41514963 0.15558505 0.42926532]
 [0.44915144 0.15009118 0.40075737]
 [0.45214956 0.15247169 0.39537876]
 [0.44972802 0.16321312 0.38705886]
 [0.43479535 0.15645844 0.40874621]
 [0.42310482 0.17341374 0.40348145]
 [0.4336153  0.17309293 0.39329177]
 [0.45661383 0.17155924 0.37182694]
 [0.43953408 0.16967044 0.39079548]]

     Asset1    Asset2    Asset3  Portfolio               Value
0 -0.024677  0.157992 -0.089881  -0.023153        Total Return
1 -0.012221  0.024968 -0.035901  -0.023153  Return Attribution
2  0.012564  0.000161  0.021275   0.033999     Vol Attribution


In [11]:
data5 = pd.read_csv('problem5.csv', index_col=4)
returns = data5.pct_change().dropna()

In [12]:
returns.head(10)

Price1    Price2    Price3    Price4
Date                                              
2023-03-03 -0.000110 -0.000467  0.000611 -0.000414
2023-03-04  0.000092 -0.000005 -0.000620 -0.000242
2023-03-05 -0.000369  0.000589  0.000354  0.000513
2023-03-06  0.000384  0.000047 -0.000299  0.000061
2023-03-07 -0.000591 -0.000686  0.000403 -0.000869
2023-03-08  0.000086  0.000395 -0.000617 -0.000393
2023-03-09  0.000282 -0.000311  0.000410  0.000524
2023-03-10 -0.000127 -0.000296 -0.000011 -0.000054
2023-03-11  0.000146  0.000641  0.000205  0.000272
2023-03-12  0.000609  0.000215  0.000194 -0.000166